<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Bai4_4_AvatarCsv</RootNamespace>
    <AssemblyName>Bai4_4_AvatarCsv</AssemblyName>
  </PropertyGroup>

</Project>
